apiVersion: v1
kind: ServiceAccount
metadata:
  name: siteabout-manager-sa
  namespace: siteabout
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-manager-role
  namespace: siteabout
rules:
  - apiGroups: ["batch", ""]
    resources: ["jobs", "pods"]
    verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-binding
  namespace: siteabout
subjects:
  - kind: ServiceAccount
    name: siteabout-manager-sa
    namespace: siteabout
roleRef:
  kind: Role
  name: job-manager-role
  apiGroup: rbac.authorization.k8s.io